routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'MainController@index')->name('main');
Route::post('/check_voucher', 'MainController@check_voucher');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/new_portal','HomeController@portal_request')->middleware('auth');
Route::post('/new_portal','RequestController@portal_request_update')->middleware('auth');

Route::group(['prefix' => 'wallet', 'middleware' => ['auth','wallet']], function () {
    
    Route::get('','WalletPanelController@index');
    Route::get('dashboard','WalletPanelController@index');
    
    Route::get('users','WalletPanelController@users');
    Route::get('users/{id}','WalletPanelController@user');
    Route::get('users/{id}/edit','WalletPanelController@user_edit');
    Route::get('/users_dt_ajax', 'WalletPanelController@user_dtajax');    
    
    Route::get('reseller','WalletPanelController@reseller');
    
    Route::get('vouchers','WalletPanelController@index');
    Route::get('/voucher/{ids}','WalletPanelController@voucher_print');
    Route::get('/voucher/{id}/row','WalletPanelController@voucher_print_rfresh');
    Route::get('/voucher/{id}/sold','WalletPanelController@voucher_sold');
    Route::get('/voucher/{id}/refund','WalletPanelController@voucher_refund');
    Route::get('/vouchers','WalletPanelController@voucher_list');    
    Route::get('/vouchers_dt_ajax', 'WalletPanelController@dtajax');
    
    Route::get('/vouchers/{action}/{ids}','WalletPanelController@vouchers_actions');
    Route::get('/vouchers/{action}/{ids}','WalletPanelController@vouchers_actions');
    Route::get('/vouchers/{action}/{ids}','WalletPanelController@vouchers_actions');
    
});

Route::group(['prefix' => 'portalpanel', 'middleware' => ['auth','portal_wallet']], function () {
    
    Route::get('','PortalPanelController@index');
    Route::get('dashboard','PortalPanelController@index');
    Route::get('portal/edit','PortalPanelController@edit');
    Route::post('portal/update/{portal_id}','PortalPanelController@update');    
        
    Route::get('/vouchers','PortalPanelController@voucher_list');    
    Route::get('/vouchers_dt_ajax', 'PortalPanelController@dtajax');
    
    Route::get('/apikey/{portal_id}', 'ApiKeyController@get_key_portal');
    Route::get('/apikey/{portal_id}/change', 'ApiKeyController@change_key_portal');
    
});

Route::group(['prefix' => 'adminpanel', 'middleware' => ['auth','admin_wallet']], function () {
    
    Route::get('','WalletAdminPanelController@index');
    Route::get('dashboard','WalletAdminPanelController@index');
    
    Route::resource('roles','RoleController');
    Route::get('/roles_dt_ajax', 'RoleController@dtajax');
    
    Route::resource('resellers','ResellerController');
    Route::get('/resellers_dt_ajax', 'ResellerController@dtajax');
    Route::get('/resellers_dt_ajax/{id}', 'UserController@dtajax_reseller');
    
    Route::resource('voucherprice','VoucherTypeController');
    Route::get('/voucherprice_dt_ajax', 'VoucherTypeController@dtajax');
    
    Route::resource('users','UserController');
    Route::get('/user_dt_ajax', 'UserController@dtajax');    
    
    Route::resource('vouchers','VoucherController');
    Route::get('/voucher/{id}','VoucherController@voucher_show');
    Route::get('/vouchers_dt_ajax', 'VoucherController@dtajax');
    
    Route::get('/apikey/{portal_id}', 'ApiKeyController@get_key');
    Route::get('/apikey/{portal_id}/change', 'ApiKeyController@change_key');
    
    Route::resource('settings','SettingsController');
    Route::get('/settings_portal','SettingsController@portal_settings');    
    
    Route::get('/requests/portal','RequestController@portal_index');  
    Route::get('/requests/portal/{id}','RequestController@portal_show'); 
    Route::get('/requests/portal/{id}/approve','RequestController@portal_approve');     
    Route::get('/requests/portal/{id}/disable','RequestController@portal_disable');     
    Route::delete('/requests/portal/{id}','RequestController@portal_delete');     
    Route::get('/requests/portal_dt_ajax', 'RequestController@portal_dtajax');
            
    Route::resource('portal','PortalController');    
    Route::get('/portal_dt_ajax', 'PortalController@dtajax');
    Route::get('/portal/{id}/disable', 'PortalController@disable');            
        
});

app/Http/Controllers/WalletAdminPanelController.php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use App\Voucher;


class WalletAdminPanelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:admin_panel');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
	$vaucher_count = Voucher::count();
	$vaucher_count_sold = Voucher::where('status','sold')->count();
	$vaucher_count_active = Voucher::where('status','activate')->count();
	$total_users = Voucher::whereNotNull('user_id')->distinct('user_id')->count('user_id');
        
        return view('WalletAdminPanel.dashboard', compact('vaucher_count','vaucher_count_sold','vaucher_count_active','total_users'));
    }


}

resources/views/WalletAdminPanel/voucherprice/create.blade.php
@extends('WalletAdminPanel.layouts.app')

@section('htmlheader_title') {{ __('Create Voucher Price') }} @endsection

@section('main-content')

<header class="PageHeader">
    <h1 class="PageTitle"> {{ __('Create New Voucher Price') }} </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            
            <div class="card-title">
                <div class="row">

                    <div class="col-md-6">                        
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>

                    <div class="col-md-6 -text-right">
                        <a class="btn btn-success  btn-sm" role="button" href="{{ route('voucherprice.index') }}"> {{ __('Back to Voucher Price List') }}</a>                        
                    </div>

                </div>
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">                                                                        
                        
                        {!! Form::open(array('route' => 'voucherprice.store','method'=>'POST')) !!}
                        <div class="row">
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                </div>
                            </div>-->
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Price:</strong>
                                    {!! Form::text('price', null, array('placeholder' => 'Price','class' => 'form-control')) !!}
                                </div>
                            </div>                                                        
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Validity:</strong>
                                    {!! Form::text('validity', null, array('placeholder' => 'validity','class' => 'form-control')) !!}                               
                                </div>
                            </div>-->
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                        
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

@push('styles')
        
@endpush

@push('scripts')
    
    <script>
    $(function () {
        
    });
    </script>
    
@endpush

resources/views/WalletAdminPanel/voucherprice/edit.blade.php
@extends('WalletAdminPanel.layouts.app')

@section('htmlheader_title') {{ __('Edit Voucher Price') }} @endsection

@section('main-content')

<header class="PageHeader">
    <h1 class="PageTitle"> {{ __('Edit Voucher Price') }} </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            
            <div class="card-title">
                <div class="row">

                    <div class="col-md-6">                        
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>

                    <div class="col-md-6 -text-right">
                        <a class="btn btn-success  btn-sm" role="button" href="{{ route('voucherprice.index') }}"> {{ __('Back to Voucher Prices List') }}</a>                        
                    </div>

                </div>
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">    
                        {!! Form::model($vouchertype, ['method' => 'PATCH','route' => ['voucherprice.update', $vouchertype->id]]) !!}
                        <div class="row">
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                </div>
                            </div>-->
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Price:</strong>
                                    {!! Form::text('price', null, array('placeholder' => 'Price','class' => 'form-control')) !!}
                                </div>
                            </div>                                                        
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Validity:</strong>
                                    {!! Form::text('validity', null, array('placeholder' => 'Price','class' => 'form-control')) !!}                                            
                                </div>
                            </div>-->
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                                                
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

@push('styles')
        
@endpush

@push('scripts')
    
    <script>
    $(function () {
        
    });
    </script>
    
@endpush

resources/views/WalletAdminPanel/voucherprice/index.blade.php
@extends('WalletAdminPanel.layouts.app')

@section('htmlheader_title') {{ __('Voucher Prices List') }} @endsection

@section('main-content')

<header class="PageHeader">
    <h1 class="PageTitle"> {{ __('Voucher Prices List') }} </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            
            <div class="card-title">
                <div class="row">

                    <div class="col-md-6">
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                        @endif
                    </div>

                    <div class="col-md-6 -text-right">
                        @if(Auth::user()->hasPermissionTo('voucher-type-create'))
                        <a class="btn btn-success  btn-sm" role="button" href="{{ route('voucherprice.create') }}"> {{ __('Create New Voucher Price') }}</a>     
                        @endif
                    </div>

                </div>
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">                                                                        
                        <table id="resellers_table" class="table table-responsive-lg table-bordered table-hover">
                            <thead>
                                <tr class="success">
                                    <th>No</th>
                                    <!--<th>Name</th>-->
                                    <th>Price</th>
                                    <!--<th>Validity</th>-->
                                    <th>Action</th>
                                </tr>
                            </thead>
                            
                            <tbody></tbody>
                        </table>
                        
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

@if(Auth::user()->hasPermissionTo('voucher-type-delete'))
<div style="display: none">
    <form id="jq_resellers-delete-form" method="POST" action="" data-url="{{ url('/adminpanel/voucherprice/') }}" accept-charset="UTF-8">
        @csrf
        <input name="_method" type="hidden" value="DELETE">    
        <input class="btn btn-danger" type="submit" value="Delete">
    </form>
</div>
@endif

@endsection

@push('styles')

    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/DataTables/datatables.min.css') }}"/>
    
@endpush

@push('scripts')
    
    <script src="{{ asset('plugins/DataTables/datatables.min.js') }}"></script>
    
    <script>
    $(function () {
            $("#resellers_table").DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ url('adminpanel/voucherprice_dt_ajax') }}",
                language: {
                    lengthMenu: "_MENU_",
                    search: "_INPUT_",
                    searchPlaceholder: "{{ __('Search') }}"
                    },
            columns: [
                {   data: 'id' },
//                {   data: 'name' },
                {   data: 'price' },
//                {   data: 'validity'},                
                {   data: 'actions',
                    orderable: false,
                    render: function ( data, type, row ) {
                        var actions = '';
                        
                        actions += '<div class="btn-group btn-group-sm" style="margin:0 5px;" role="group" aria-label="Basic example">';
                        actions += '<a href="{{ url('adminpanel/voucherprice') }}/'+row.id+'" class="btn btn-success"><i class="icon-eye icons"></i></a>';
                        actions += '</div>';
                        
                        @if(Auth::user()->hasPermissionTo('voucher-type-edit'))
                        actions += '<div class="btn-group btn-group-sm" style="margin:0 5px;" role="group" aria-label="Basic example">';
                        actions += '<a href="{{ url('adminpanel/voucherprice') }}/'+row.id+'/edit" class="btn btn-primary"><i class="icon-pencil icons"></i></a>';
                        actions += '</div>';
                        @endif
                        
                        @if(Auth::user()->hasPermissionTo('voucher-type-delete'))
                        if(row.status != 'deleted'){                            
                            actions += '<div class="btn-group btn-group-sm" style="margin:0 5px;" role="group" aria-label="Basic example">';                        
                            actions += '<a href="" class="btn btn-danger jq_resellers-delete" data-resellers_id="'+row.id+'"><i class="icon-trash icons"></i></a>';
                            actions += '</div>';
                        }
                        @endif
                        
                        return actions;
                    }
                }
            ]
            });
            
        $(document).on('click','.jq_resellers-delete',function (e){
            e.preventDefault(); 
            $('#jq_resellers-delete-form').attr('action',$('#jq_resellers-delete-form').attr('data-url')+ '/' + $(this).attr('data-resellers_id'));
            $('#jq_resellers-delete-form').submit();
        });    
            
    });
    </script>
    
@endpush

resources/views/WalletAdminPanel/voucherprice/show.blade.php
@extends('WalletAdminPanel.layouts.app')

@section('htmlheader_title') {{ __('Voucher Price') }} @endsection

@section('main-content')

<header class="PageHeader">
    <h1 class="PageTitle"> {{ __('Voucher Price') }} </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            
            <div class="card-title">
                <div class="row">

                    <div class="col-md-6">                        
                        {{$vouchertype->price}}
                    </div>

                    <div class="col-md-6 -text-right">
                        <a class="btn btn-success  btn-sm" role="button" href="{{ route('voucherprice.index') }}"> {{ __('Back to Voucher Prices List') }}</a>                        
                    </div>

                </div>
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">                                                                        
                        <div class="row">
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {{$vouchertype->name}}                                    
                                </div>
                            </div>-->
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Price:</strong>
                                    {{$vouchertype->price}}
                                </div>
                            </div>                                                        
<!--                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Validity, days:</strong>
                                    {{$vouchertype->validity}}
                                </div>
                            </div>                            -->
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection